# Generated by Django 4.2 on 2023-08-13 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_name_order_phone_number_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
    ]
