# Generated by Django 4.2.5 on 2024-02-02 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=13, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(11, 'Incorrect phone number format.')])),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_order_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(1, 'Created'), (2, 'Paid'), (3, 'Processing'), (4, 'Done'), (0, 'Cancelled')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=10, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[(1, 'Created'), (2, 'Paid'), (3, 'Sent'), (4, 'Received'), (0, 'Cancelled')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'ordering': ['status', '-timestamp'],
            },
        ),
    ]
