# Generated by Django 4.2.5 on 2024-02-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Cancelled'), (1, 'Created'), (2, 'Paid'), (3, 'Processing'), (4, 'Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[(0, 'Cancelled'), (1, 'Created'), (2, 'Paid'), (3, 'Sent'), (4, 'Received')], max_length=20),
        ),
    ]
