# Generated by Django 4.2.5 on 2024-03-30 20:30

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_answer_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.ProductImage.get_upload_to),
        ),
    ]
