# Generated by Django 4.2.5 on 2024-02-02 21:23

from django.db import migrations, models
import django.db.models.deletion
import fandoms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fandom_type', models.CharField(choices=[('Games', 'Games'), ('Anime', 'Anime'), ('Series', 'Series'), ('Movies', 'Movies'), ('Cartoons', 'Cartoons'), ('Other', 'Other')], max_length=10)),
                ('image', models.ImageField(default='fandom_images/No_image_available.png', upload_to=fandoms.models.Fandom.get_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='character_images/No_image_available.png', upload_to=fandoms.models.Character.get_upload_to)),
                ('fandom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='fandoms.fandom')),
            ],
        ),
    ]
