# Generated by Django 4.2.5 on 2024-02-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandoms', '0002_alter_character_image_alter_fandom_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='fandom',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fandom',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
