# Generated by Django 4.2.5 on 2024-03-30 20:30

from django.db import migrations, models
import fandoms.models


class Migration(migrations.Migration):

    dependencies = [
        ('fandoms', '0003_alter_character_options_alter_fandom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=fandoms.models.Character.get_upload_to),
        ),
        migrations.AlterField(
            model_name='fandom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=fandoms.models.Fandom.get_upload_to),
        ),
    ]
