# Generated by Django 4.2.5 on 2024-02-02 21:23

import django.core.validators
from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('organization_type', models.CharField(choices=[('IE', 'Individual Entrepreneur'), ('LLC', 'LLC'), ('JSC', 'JCS'), ('SE', 'Self-Employed')], max_length=50)),
                ('organization_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('taxpayer_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'Incorrect ITN format.')])),
                ('check_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(20, 'Incorrect check format.')])),
                ('balance', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_admin_store', models.BooleanField(default=False)),
                ('logo', models.ImageField(default='store_logos/no-photo-available-icon-20.jpg', upload_to=stores.models.Store.get_upload_to)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
