# Generated by Django 4.2.5 on 2024-02-20 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='check_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(20, 'Incorrect check format.')]),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='taxpayer_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'Incorrect ITN format.')]),
        ),
    ]
