# Generated by Django 4.2.5 on 2024-03-30 20:30

from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_employee_options_alter_store_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=stores.models.Store.get_upload_to),
        ),
    ]
