# Generated by Django 4.2.5 on 2024-02-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
    ]
