# Generated by Django 4.2.5 on 2024-03-30 20:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_address_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.User.get_upload_to),
        ),
    ]
